### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by meyskens** [tonobo/mtr#1]
Hey, I plan to use this project in an (open source) project of mine so I can run something like MTR without having C dependencies. You have done a great job!

I have noticed there is no license file nor is it mentioned in the readme, would you mind adding a license so I can make sure I credit your work correctly. Thanks!

**Comment by meyskens** [comment]
Will do! I currently have a branch with all components in separate packages for import use, if you find that handy I can already PR that.

**Comment by tonobo** [comment]
Closed by 8214292
