### ISSUE TITLE
Many duplicate routes ip, loop show?

### ISSUE THREAD

**Issue by ylwang1122** [tonobo/mtr#12]
![image](https://user-images.githubusercontent.com/29241786/58100289-e92e7380-7c0f-11e9-9fea-4beaff5103b7.png)

Using linux's MTR is inconsistent with the result of this time. It should be that there is something wrong with the program, but I did not find it out.

**Comment by tonobo** [comment]
hnm really strange. could you post the original mtr as well. its petty hard to catch such issues without reproducing them.

**Comment by ylwang1122** [comment]
![image](https://user-images.githubusercontent.com/29241786/58144283-5974dd80-7c80-11e9-9c4f-86b1f0fd8cd5.png)
that is linux's MTR results.

**Comment by ylwang1122** [comment]
I found the problem！！！

First:
https://github.com/tonobo/mtr/blob/cfb8cee1868883a2d2184e4da35ac1163cec518a/pkg/icmp/icmp.go#L207
The value of index should not be calculated this way. It is verified by the program that this calculation method is wrong and cannot get the correct result.Should be set: index=20。

Second:
https://github.com/tonobo/mtr/blob/cfb8cee1868883a2d2184e4da35ac1163cec518a/pkg/icmp/icmp.go#L212
Not only does the seq need to be verified here, but the ID of the icmp package also needs to be verified.If a machine executes the mtr program concurrently, an abnormal result will occur.
`		
		if typ, ok := x.Type.(ipv4.ICMPType); ok && typ.String() == "time exceeded" {
			body := x.Body.(*icmp.TimeExceeded).Data

			x, _ := icmp.ParseMessage(ProtocolICMP, body[20:])
			switch x.Body.(type) {
			case *icmp.Echo:
				id := x.Body.(*icmp.Echo).ID
				seq := x.Body.(*icmp.Echo).Seq
				if id == needId &&  seq == needSeq {
					return peer.String(), []byte{}, nil
				}
			default:
				// ignore
			}
		}

		if typ, ok := x.Type.(ipv4.ICMPType); ok && typ.String() == "echo reply" {
			b, _ := x.Body.Marshal(ProtocolICMP)
			if string(b[4:]) != string(neededBody) {
				continue
			}
			if x.Body.(*icmp.Echo).ID != needId {
				continue
			}

			return peer.String(), b[4:], nil
		}
`
The above is the conclusion I got through the capture of the package, please check

**Comment by boobieliu** [comment]
(⊙o⊙)…
I found the same problem.
![image](https://user-images.githubusercontent.com/14822284/58149091-0016a980-7c94-11e9-9655-ef6b5dc6e518.png)

**Comment by ylwang1122** [comment]
@boobieliu 问题的根源在于对icmp回传的数据包验证不足，增加id验证即可解决这个问题。在选取pid的时候需要使用goroutine的id（目的是保持并发的mtr探测所使用的pid不同）。

**Comment by boobieliu** [comment]
@ylwang1122 多谢，关于使用协程id的情况，我再请教下，一开始我以为是并发协程之间返回数据导致数据重复，但是通过打印，根据ttl看起来并不会引起冲突。

**Comment by ylwang1122** [comment]
@boobieliu 可设定ttl为1，多ip地址并发发起mtr探测，可以验证结果。某一个协程可能会收到另一个协程发起的icmp数据包的返回结果，并进行解析，造成结果的混乱。因此需要对接收到的icmp返回包进行验证是否是本协程发出的，来决定丢弃处理还是解析保留。

**Comment by boobieliu** [comment]
@ylwang1122 了解，多谢
