### ISSUE TITLE
Get wrong route when making mtr from server in china to server in hongkong 

### ISSUE THREAD

**Issue by SgtDaJim** [tonobo/mtr#5]
Hi, @tonobo , here is the screenshot:
![image](https://user-images.githubusercontent.com/10288044/52625967-2686b500-2eed-11e9-9fbe-f72063fc1100.png)
and the 127.0.0.1 in red square is absolutely non-sense.
Could you please check this out ?

**Comment by SgtDaJim** [comment]
btw, 192.254.94.28 is one of my server, so it must be a wrong route node, either.

**Comment by tonobo** [comment]
I'll try to figure out where the issue comes from. Thank you for reporting

**Comment by tonobo** [comment]
Could you paste the same route using original mtr?

**Comment by SgtDaJim** [comment]
Here is the result made by official mtr v0.92
![image](https://user-images.githubusercontent.com/10288044/52628731-386b5680-2ef3-11e9-89c3-9e43689f02e3.png)

**Comment by SgtDaJim** [comment]
Hi @tonobo , is there any progress on this pr?

**Comment by SgtDaJim** [comment]
Hi @tonobo , is there any progress on this pr?
