### ISSUE TITLE
Error: GetWinsize: inappropriate ioctl for device

### ISSUE THREAD

**Issue by sedlund** [tonobo/mtr#9]
Getting this error on a MIPS based device.  

> root@localhost:/usr/bin# gomtr 1.1.1.1
> Start: 2019-02-20 19:24:20.633342142 +0000 UTC m=+0.019848589
> Error: GetWinsize: inappropriate ioctl for device
> Error: GetWinsize: inappropriate ioctl for device
> Error: GetWinsize: inappropriate ioctl for device
> Error: GetWinsize: inappropriate ioctl for device
> Error: GetWinsize: inappropriate ioctl for device
> Error: GetWinsize: inappropriate ioctl for device
> Error: GetWinsize: inappropriate ioctl for device
> Error: GetWinsize: inappropriate ioctl for device
> Error: GetWinsize: inappropriate ioctl for device
> Error: GetWinsize: inappropriate ioctl for device
> Error: GetWinsize: inappropriate ioctl for device
> Error: GetWinsize: inappropriate ioctl for device
> Error: GetWinsize: inappropriate ioctl for device
> Error: GetWinsize: inappropriate ioctl for device
> Error: GetWinsize: inappropriate ioctl for device
> Error: GetWinsize: inappropriate ioctl for device
> Error: GetWinsize: inappropriate ioctl for device
> Error: GetWinsize: inappropriate ioctl for device
> Error: GetWinsize: inappropriate ioctl for device
> Error: GetWinsize: inappropriate ioctl for device
> Error: GetWinsize: inappropriate ioctl for device
> Error: GetWinsize: inappropriate ioctl for device
> Error: GetWinsize: inappropriate ioctl for device
> Error: GetWinsize: inappropriate ioctl for device
> Error: GetWinsize: inappropriate ioctl for device
> Error: GetWinsize: inappropriate ioctl for device
> Error: GetWinsize: inappropriate ioctl for device
> Error: GetWinsize: inappropriate ioctl for device
> Error: GetWinsize: inappropriate ioctl for device
> 

Think this was fixed in this patch:

https://github.com/buger/goterm/commit/2f70ee476a85f692e8d4265963c615d8a57652da

Edit:

I can confirm that updating buger/goterm and golang.org/x/sys/unix fixes the issue.

**Comment by tonobo** [comment]
Okay, great. I'll update vendor ;)
